### PR TITLE
Handle https://github.com/dillon-giacoppo/rules_python_external/issues/8

### PR DESCRIPTION
**Pull request by thundergolfer**
### Description 

See title.

### CODE REVIEW

**Review by dillon-giacoppo — APPROVED** [review]
LGTM

**Comment by thundergolfer** [comment]
Wow, super quick on the review 😅.

**Comment by thundergolfer** [comment]
I'm testing it more thoroughly now.

**Comment by thundergolfer** [comment]
Works fine with TF `2.0.0`

**Comment by thundergolfer** [comment]
Works fine with TF `1.14.0` 

(tested locally with the `canva/data-science` repo.

**Comment by thundergolfer** [comment]
Confident enough with won't create a regression that we care about, and get's TF 2.0.0 working again, so while it's not great code at all I'll merge it.

**Pull request merged**
