### PR TITLE
Allow users to pass in an alternate rule deps specifications.

### PR DESCRIPTION
**Pull request by hrfuller**
I need this to allow me to download the rule deps wheels from an alternate hosting location. Would you be interested in upstreaming this change?

### CODE REVIEW

**Comment by dillon-giacoppo** [comment]
Thanks for the contribution. In it's current form, I have a few issues with the change. It does not seem great from a usability perspective, for example: if the rule deps are updated, there is no guarantee that `dep_specs` will be updated by all the consumers leading to instability for the consumers.

Would it be possible to rather than supply a full `dep_specs` to add an optional parameter that overrides the hostname `files.pythonhosted.org/` to an alternative mirror url prefix. Then package updates should automatically be pulled in assuming the mirror is in sync.

If a mirror is not sufficient, for example you want to pull in a different version of a package, I don't think that's behaviour that lives in the upstream rules. For this case you can create arbitrary wheels with the names `pypi__*` and they will override the default dependencies (because we use the maybe function).

**Comment by hrfuller** [comment]
Thanks for the feedback. Changing the hostname would suffice for my use case. I'll make the change.

**Comment by hrfuller** [comment]
Hey @dillon-giacoppo anything else needed here?

**Comment by alexeagle** [comment]
Note, these rules have been migrated to upstream (rules_python) so we'll want the same change there after this lands. (I dunno if @dillon-giacoppo has plans to keep maintaining/releasing this one, also I imagine it should be archived soon?)

**Comment by hrfuller** [comment]
@alexeagle I'm happy to apply this change to rules_python if you are interested in it.

**Comment by alexeagle** [comment]
Yeah I think that's a good idea

**Comment by alexeagle** [comment]
Looks like this should be closed since it was transferred to the upstream in https://github.com/bazelbuild/rules_python/pull/362

**Comment by dillon-giacoppo** [comment]
Closed as handled upstream and archiving this repo

**Pull request closed without merging**
