### PR TITLE
Support purelib (for Tensorflow 1.*)

### PR DESCRIPTION
**Pull request by thundergolfer**
### Description 

This includes changes from https://github.com/dillon-giacoppo/rules_python_external/pull/5, so ignore this until that is merged.

### CODE REVIEW

**Review by dillon-giacoppo — APPROVED** [review]
Also LGTM.

**Comment by thundergolfer** [comment]
@dillon-giacoppo 

Tests are broken because now they're trying to pull in the vendored `pkginfo` (`namespace_pkgs` -> `wheel` -> `pkginfo`). 

```
INFO: Analyzed 2 targets (1 packages loaded, 9 targets configured).
INFO: Found 1 target and 1 test target...
FAIL: //src:test (see /private/var/tmp/_bazel_jbelotti/3c60bd2bbdf77a931dd1e4480754fe7a/execroot/rules_python_external/bazel-out/darwin-fastbuild/testlogs/src/test/test.log)
INFO: From Testing //src:test:
==================== Test output for //src:test:
E
======================================================================
ERROR: src.tests.test_namespace_pkgs (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: src.tests.test_namespace_pkgs
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/private/var/tmp/_bazel_jbelotti/3c60bd2bbdf77a931dd1e4480754fe7a/sandbox/darwin-sandbox/9/execroot/rules_python_external/bazel-out/darwin-fastbuild/bin/src/test.runfiles/rules_python_external/src/tests/test_namespace_pkgs.py", line 6, in <module>
    import src.namespace_pkgs
  File "/private/var/tmp/_bazel_jbelotti/3c60bd2bbdf77a931dd1e4480754fe7a/sandbox/darwin-sandbox/9/execroot/rules_python_external/bazel-out/darwin-fastbuild/bin/src/test.runfiles/rules_python_external/src/namespace_pkgs.py", line 4, in <module>
    from . import wheel
  File "/private/var/tmp/_bazel_jbelotti/3c60bd2bbdf77a931dd1e4480754fe7a/sandbox/darwin-sandbox/9/execroot/rules_python_external/bazel-out/darwin-fastbuild/bin/src/test.runfiles/rules_python_external/src/wheel.py", line 2, in <module>
    import pkginfo
ModuleNotFoundError: No module named 'pkginfo'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
================================================================================
INFO: Elapsed time: 0.487s, Critical Path: 0.36s
INFO: 2 processes: 2 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 4 total actions
//src:test                                                               FAILED in 0.3s
  /private/var/tmp/_bazel_jbelotti/3c60bd2bbdf77a931dd1e4480754fe7a/execroot/rules_python_external/bazel-out/darwin-fastbuild/testlogs/src/test/test.log

INFO: Build completed, 1 test FAILED, 4 total actions
```

I'll trying wrapping up `pkginfo` in `py_library` and giving it to `:src`.

**Comment by dillon-giacoppo** [comment]
We probably just want to move the PATH logic in `tools/wheel_wrapper.py` to an __init__.py in the src directory.

**Comment by thundergolfer** [comment]
I think we'd prefer to have Bazel manage the `PYTHONPATH` as much as possible for this. As in, use Bazel's `py_library` to describe the dependency of `wheel.py` on `pkginfo` and not hack the PYTHONPATH to have it work. 

Though it is probably also better that that logic moves to `__init__.py`.

**Comment by dillon-giacoppo** [comment]
The issue is, the script is run directly with repo_ctx.execute not as a py_binary. Therefore we will need to construct the path in the __init__.py anyway for the actual execution. IIUC doing it with Bazel means we have to define it twice. If there is a way to do it cleanly, I am all for it.

**Comment by thundergolfer** [comment]
> The issue is, the script is run directly with repo_ctx.execute not as a py_binary.

I think I can fix this test issue with one `py_library` for `pkginfo` and put that in `deps` of the existing `:src` target. That fixes the tests and doesn't affect the existing `repo_ctx.execute`.

**Comment by thundergolfer** [comment]
@dillon-giacoppo what do you think of f0e29e2? All good?

**Comment by dillon-giacoppo** [comment]
LGTM. Nice!

**Pull request merged**
